"""Deterministic ranking view."""

from __future__ import annotations

from html import escape
from typing import Any

import streamlit as st

from app.services.run_state import NOT_AVAILABLE, RunSnapshot

COMPONENT_LABELS = {
    "skill_match": "Skill match",
    "experience_alignment": "Experience",
    "industry_domain_alignment": "Industry / domain",
    "location_alignment": "Location",
}


def render_ranking(snapshot: RunSnapshot) -> None:
    st.markdown(
        """
        <div class="section-heading">
          <div><div class="eyebrow">Stage 03</div><h2>Deterministic ranking</h2></div>
          <span class="source-tag">score_jobs</span>
        </div>
        <div class="deterministic-banner">
          <span class="deterministic-banner__mark">ƒ</span>
          <div>
            <strong>Calculated by deterministic scoring code — not generated by the LLM</strong>
            <p>The agent chooses the scoring tool; Python calculates every component and selects the first three ranked IDs.</p>
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    _render_formula(snapshot.scoring_weights)
    if not snapshot.evidence_available.get("ranking"):
        st.info(NOT_AVAILABLE)
        if snapshot.top_selection_source == "artifact_folders":
            st.caption(
                "Three selected-job folders exist, but no ranking artifact proves their order or scores."
            )
        return
    if not snapshot.ranked_jobs:
        st.info("The ranking artifact contains no rows.")
        return
    top_ids = (
        set(snapshot.top_3_job_ids)
        if snapshot.top_selection_source
        in {"live_state", "manifest", "ranked_artifact"}
        else set()
    )
    for rank, item in enumerate(snapshot.ranked_jobs, start=1):
        if not isinstance(item, dict):
            continue
        job = item.get("job", item)
        if not isinstance(job, dict):
            continue
        job_id = str(job.get("job_id") or "")
        _ranking_card(rank, job, item, job_id in top_ids)


def _render_formula(weights: dict[str, float]) -> None:
    with st.expander("Scoring formula and weights", expanded=False):
        if not weights:
            st.info(NOT_AVAILABLE)
            return
        formula = " + ".join(
            f"{weight:g} × {COMPONENT_LABELS.get(name, name)} alignment"
            for name, weight in weights.items()
        )
        st.code(f"overall_score = {formula}", language="text")
        columns = st.columns(len(weights))
        for column, (name, weight) in zip(columns, weights.items(), strict=True):
            column.metric(COMPONENT_LABELS.get(name, name), f"{weight:g}%")
        st.caption("Source: src/tools/filtering_scoring/scoring.py · SCORING_WEIGHTS")


def _ranking_card(
    rank: int,
    job: dict[str, Any],
    scored: dict[str, Any],
    is_top: bool,
) -> None:
    title = str(job.get("title") or "Untitled role")
    company = str(job.get("company") or "Company unavailable")
    job_id = str(job.get("job_id") or "—")
    score = scored.get("score")
    badge = '<span class="top-badge">Automatic Top 3</span>' if is_top else ""
    score_text = f"{float(score):.1f}" if isinstance(score, (int, float)) else "—"
    st.markdown(
        f"""
        <article class="ranking-card">
          <div class="rank-number">{rank:02d}</div>
          <div class="ranking-card__identity">
            <div>{badge}<span class="id-tag">{escape(job_id)}</span></div>
            <h3>{escape(title)}</h3>
            <p>{escape(company)} · {escape(str(job.get("location") or "Location unavailable"))}</p>
          </div>
          <div class="score-orb"><strong>{score_text}</strong><span>/ 100</span></div>
        </article>
        """,
        unsafe_allow_html=True,
    )
    breakdown = scored.get("score_breakdown", {})
    if isinstance(breakdown, dict) and breakdown:
        columns = st.columns(4)
        for column, (name, label) in zip(
            columns, COMPONENT_LABELS.items(), strict=True
        ):
            component = breakdown.get(name, {})
            points = component.get("points") if isinstance(component, dict) else None
            weight = component.get("weight") if isinstance(component, dict) else None
            alignment = component.get("alignment") if isinstance(component, dict) else None
            with column:
                st.metric(
                    label,
                    f"{points:g} pts" if isinstance(points, (int, float)) else "—",
                    help=(
                        f"Alignment {float(alignment):.0%} × weight {weight:g}"
                        if isinstance(alignment, (int, float))
                        and isinstance(weight, (int, float))
                        else NOT_AVAILABLE
                    ),
                )
    elif scored.get("rationale"):
        st.caption(str(scored["rationale"]))

